cmake_minimum_required(VERSION 3.25)

# SDK 6.0.9 emits these two runtime files; its worker is embedded in the loader.
# This script intentionally does not copy arbitrary sidecars from bin.
foreach(required BUILD_ROOT DESTINATION LOADER WASM ASSETS CONFIGURATION)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "Missing staging argument: ${required}")
  endif()
endforeach()
file(REAL_PATH "${BUILD_ROOT}" root)
if(EXISTS "${DESTINATION}")
  file(REAL_PATH "${DESTINATION}" destination)
else()
  cmake_path(ABSOLUTE_PATH DESTINATION NORMALIZE OUTPUT_VARIABLE destination)
endif()
if(NOT destination STREQUAL "${root}/package")
  message(FATAL_ERROR "Unsafe package destination: ${DESTINATION}; expected ${root}/package")
endif()
foreach(path "${DESTINATION}" "${root}/package.staging" "${root}/package.previous")
  if(IS_SYMLINK "${path}")
    message(FATAL_ERROR "Unsafe linked staging path: ${path}")
  endif()
endforeach()
set(inputs "${LOADER}" "${WASM}" "${ASSETS}/index.html" "${ASSETS}/serve.py" "${ASSETS}/README.md")
set(names MinimalAppSample.js MinimalAppSample.wasm index.html serve.py README.md)
foreach(input IN LISTS inputs)
  if(NOT EXISTS "${input}" OR IS_DIRECTORY "${input}")
    message(FATAL_ERROR "Missing required package input: ${input}")
  endif()
endforeach()
set(temporary "${root}/package.staging")
set(previous "${root}/package.previous")
if(EXISTS "${temporary}" OR EXISTS "${previous}")
  message(FATAL_ERROR "Staging replacement blocked: remove owned package.staging/package.previous after inspecting the prior failure")
endif()
file(MAKE_DIRECTORY "${temporary}")
set(manifest "{}")
string(JSON manifest SET "${manifest}" configuration "\"${CONFIGURATION}\"")
string(JSON manifest SET "${manifest}" sdk "\"6.0.9\"")
string(JSON manifest SET "${manifest}" files "{}")
foreach(index RANGE 0 4)
  list(GET inputs ${index} input)
  list(GET names ${index} name)
  file(COPY_FILE "${input}" "${temporary}/${name}")
  file(SHA256 "${temporary}/${name}" hash)
  string(JSON manifest SET "${manifest}" files "${name}" "\"${hash}\"")
endforeach()
file(WRITE "${temporary}/manifest.json" "${manifest}\n")
if(EXISTS "${destination}")
  file(RENAME "${destination}" "${previous}" RESULT result)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Package replacement failed: ${result}")
  endif()
endif()
file(RENAME "${temporary}" "${destination}" RESULT result)
if(NOT result STREQUAL "0")
  if(EXISTS "${previous}")
    file(RENAME "${previous}" "${destination}")
  endif()
  message(FATAL_ERROR "Package publication failed: ${result}")
endif()
if(EXISTS "${previous}")
  file(REMOVE_RECURSE "${previous}")
endif()
message(STATUS "Staged ${CONFIGURATION} web package: ${destination}")
